//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public decimal ACCOUNT_ID { get; set; }
        public decimal CLIENT_ID { get; set; }
        public Nullable<decimal> NUMBER { get; set; }
        public string IBAN { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
