//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESS
    {
        public decimal ADRESS_ID { get; set; }
        public decimal CLIENT_ID { get; set; }
        public string LINE1 { get; set; }
        public string LINE2 { get; set; }
        public string LINE3 { get; set; }
        public string POSTALCODE { get; set; }
        public string CITY { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public string TYPE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
