//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPOSED_TO
    {
        public decimal MODULE_ID { get; set; }
        public decimal COMPONENT_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual COMPONENTS COMPONENTS { get; set; }
        public virtual MODULE MODULE { get; set; }
    }
}
