//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPONENTS()
        {
            this.COMPOSED_TO = new HashSet<COMPOSED_TO>();
        }
    
        public decimal COMPONENT_ID { get; set; }
        public decimal UNIT_ID { get; set; }
        public decimal FAMILY_ID { get; set; }
        public decimal STOCK_ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> UNIT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> COST { get; set; }
    
        public virtual COMPONENTFAMILY COMPONENTFAMILY { get; set; }
        public virtual STOCK STOCK { get; set; }
        public virtual UNIT UNIT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPOSED_TO> COMPOSED_TO { get; set; }
    }
}
