//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaderaEntities : DbContext
    {
        public MaderaEntities()
            : base("name=MaderaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<ADRESS> ADRESS { get; set; }
        public virtual DbSet<COMPONENTFAMILY> COMPONENTFAMILY { get; set; }
        public virtual DbSet<COMPONENTS> COMPONENTS { get; set; }
        public virtual DbSet<COMPOSED_TO> COMPOSED_TO { get; set; }
        public virtual DbSet<COVER> COVER { get; set; }
        public virtual DbSet<CURRENCY> CURRENCY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<FILL> FILL { get; set; }
        public virtual DbSet<FINISHING> FINISHING { get; set; }
        public virtual DbSet<MODELE> MODELE { get; set; }
        public virtual DbSet<MODULE> MODULE { get; set; }
        public virtual DbSet<ORDER> ORDER { get; set; }
        public virtual DbSet<ORDERDETAILS> ORDERDETAILS { get; set; }
        public virtual DbSet<ORDERSTATUS> ORDERSTATUS { get; set; }
        public virtual DbSet<POSSESSES> POSSESSES { get; set; }
        public virtual DbSet<PROJECT> PROJECT { get; set; }
        public virtual DbSet<RANGE> RANGE { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UNIT> UNIT { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
