//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELE
    {
        public decimal MODELE_ID { get; set; }
        public Nullable<decimal> RANGE_ID { get; set; }
        public Nullable<bool> STANDARD { get; set; }
    
        public virtual RANGE RANGE { get; set; }
    }
}
