//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAILS
    {
        public decimal ODERDETAILS_ID { get; set; }
        public decimal ORDER_ID { get; set; }
        public Nullable<int> MODELE { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<System.DateTime> SHIPPINGDATE { get; set; }
        public Nullable<int> SHIPPINGADRESS { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual ORDER ORDER { get; set; }
    }
}
