//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSSESSES
    {
        public decimal RANGE_ID { get; set; }
        public decimal COVER_ID { get; set; }
        public decimal FINISHING_ID { get; set; }
        public decimal FILL_ID { get; set; }
    
        public virtual COVER COVER { get; set; }
        public virtual FILL FILL { get; set; }
        public virtual FINISHING FINISHING { get; set; }
        public virtual RANGE RANGE { get; set; }
    }
}
